name: Release Java service
description: Test, build and deploy a Java service
inputs:
  name:
    description: Name of project to build
    required: false
    default: ${{ github.event.repository.name }}
  java-version:
    description: JDK version
    required: false
    default: "1.11"
  access-key:
    description: AWS Access Key
    required: true
  secret:
    description: AWS Secret
    required: true
  region:
    description: AWS Region
    required: false
    default: eu-west-2
  chartmuseum-url:
    description: URL of Chart Museum
    required: true
  chartmuseum-username:
    description: User name for Chart Museum
    required: true
  chartmuseum-password:
    description: Password for Chart Museum
    required: true
  slack-webhook-url:
    description: URL of Slack Webhook to notify
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: riskfintech-ltd/devops-actions/prepare-build@v3
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java-version }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - uses: riskfintech-ltd/devops-actions/publish-ecr/with-gradle@main
      with:
        access-key: ${{ inputs.access-key }}
        secret: ${{ inputs.secret }}
        region: ${{ inputs.region }}
    - uses: riskfintech-ltd/devops-actions/helm@v3
      with:
        chartmuseum-url: ${{ inputs.chartmuseum-url }}
        chartmuseum-username: ${{ inputs.chartmuseum-username }}
        chartmuseum-password: ${{ inputs.chartmuseum-password }}
    - uses: the-model-vault/devops-actions/slack@v3
      with:
        slack-webhook-url: ${{ inputs.slack-webhook-url }}
