name: Publish to ECR
description: Build docker image and publish it to ECR
inputs:
  access-key:
    description: AWS Access Key
    required: true
  secret:
    description: AWS Secret
    required: true
  region:
    description: AWS Region
    required: false
    default: eu-west-2
  run-before-build:
    description: Command that should be run before build
    required: false
    default: ""
outputs:
  image:
    description: Docker image
    value: ${{ env.image }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access-key }}
        aws-secret-access-key: ${{ inputs.secret }}
        aws-region: ${{ inputs.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Init build with custom command
      if: inputs.run-before-build != ''
      run: |
        ${{ inputs.run-before-build }}
      shell: bash
    - name: Build, tag, and push image to Amazon ECR
      id: docker
      env:
        DOCKER_BUILDKIT: '1'
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ecr_repository }}:${{ env.build_version }}
      run: |
        echo "image=$IMAGE" >> $GITHUB_ENV
        ./gradlew test -Djib.to.image=$IMAGE jibDockerBuild
        docker push $IMAGE
        echo "::set-output name=image::$IMAGE"
      shell: bash
